
  const defaultArray = [
    {
        "id": 1,
        "name": "Indirect Sales Channel",
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "Sales Channel",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "District 4",
        "children": [
            {
                "id": 243,
                "name": "Ahmed Seddiqi & Sons",
                "commercialNameLang1": "Ahmed Seddiqi & Sons",
                "commercialNameLang2": "أحمد صديقي & سنس",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "children": [
                    {
                        "id": 246,
                        "name": "POS Shop",
                        "commercialNameLang1": "Ahmad Traders",
                        "commercialNameLang2": "تجار احمد",
                        "dealerType": "pos_shop",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 2",
                      
                    },
                    {
                        "id": 273,
                        "name": "POS Shop",
                        "commercialNameLang1": "shafiq test",
                        "commercialNameLang2": "test arabic",
                        "dealerType": "pos_shop",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 1",
                        
                    },
                    {
                        "id": 336,
                        "name": "ghufran english",
                        "commercialNameLang1": "ghufran english",
                        "commercialNameLang2": "ghufran arabic",
                        "dealerType": "sub_distributor",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 1",
                        "children": [
                            {
                                "id": 339,
                                "name": "fauji pos shop english",
                                "commercialNameLang1": "fauji pos shop english",
                                "commercialNameLang2": "fauji pos shop in arabic",
                                "dealerType": "pos_shop",
                                "region": null,
                                "province": null,
                                "city": null,
                                "district": null,
                               
                            }
                        ]
                    },
                    {
                        "id": 348,
                        "name": "qqqq",
                        "commercialNameLang1": "qqqq",
                        "commercialNameLang2": "qqqqq",
                        "dealerType": "sub_distributor",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 1",
                        
                    },
                    {
                        "id": 354,
                        "name": "curat",
                        "commercialNameLang1": "curat",
                        "commercialNameLang2": "curat",
                        "dealerType": "sub_distributor",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 1",
                     
                    },
                    {
                        "id": 384,
                        "name": "friday sub dist",
                        "commercialNameLang1": "friday sub dist",
                        "commercialNameLang2": "frinday sub dist arabic",
                        "dealerType": "sub_distributor",
                        "region": "East",
                        "province": "East - province 1",
                        "city": "City 1",
                        "district": "District 1",
                       
                        
                    }
                ]
            },
            {
                "id": 270,
                "name": "Distributor",
                "commercialNameLang1": "Test name english",
                "commercialNameLang2": "test name arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                
                
            },
            {
                "id": 276,
                "name": "Distributor",
                "commercialNameLang1": "shafiq english",
                "commercialNameLang2": "shafiq arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                
                
            },
            {
                "id": 279,
                "name": "Distributor",
                "commercialNameLang1": "final sh english",
                "commercialNameLang2": "final sh arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 282,
                "name": "Distributor",
                "commercialNameLang1": "fresh english",
                "commercialNameLang2": "fresh arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 288,
                "name": "Test distributor",
                "commercialNameLang1": "Distributor name in english",
                "commercialNameLang2": "Distributor name in arabic",
                "dealerType": "distributor",
                "region": null,
                "province": null,
                "city": null,
                "district": null,
                "some":"other"
            },
            {
                "id": 291,
                "name": "test english new",
                "commercialNameLang1": "test english new",
                "commercialNameLang2": "test arabic new",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 324,
                "name": "english new",
                "commercialNameLang1": "english new",
                "commercialNameLang2": "arabic new",
                "dealerType": "sub_distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 327,
                "name": "test english khan",
                "commercialNameLang1": "test english khan",
                "commercialNameLang2": "test english arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 330,
                "name": "test new sub",
                "commercialNameLang1": "test new sub",
                "commercialNameLang2": "tst new sub arabic",
                "dealerType": "sub_distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 333,
                "name": "waji name english",
                "commercialNameLang1": "waji name english",
                "commercialNameLang2": "waji name arabic",
                "dealerType": "sub_distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 342,
                "name": "Ali",
                "commercialNameLang1": "Ali",
                "commercialNameLang2": "Ali",
                "dealerType": "sub_distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            }
        ]
    },
    {
        "id": 2,
        "name": "Direct Sales Channel",
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "Sales Channel",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "District 4",
        "children": [
            {
                "id": 258,
                "name": "Agency",
                "commercialNameLang1": "Al-Haneya",
                "commercialNameLang2": "الهنية",
                "dealerType": "agency",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            },
            {
                "id": 267,
                "name": "Shafiq Distributor",
                "commercialNameLang1": "Shafiq Distributor",
                "commercialNameLang2": "Shaaafique arabic",
                "dealerType": "distributor",
                "region": "East",
                "province": "East - province 1",
                "city": "City 1",
                "district": "District 1",
                "some":"other"
            }
        ]
    },
    {
        "id": 3,
        "name": "Retail",
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "Sales Channel",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "Disctrict 5",
        "children": [
            {
                "id": 255,
                "name": "Retail Shop",
                "commercialNameLang1": "Salam Shop Riyadh",
                "commercialNameLang2": "سلام شوب الرياض",
                "dealerType": "retail_shop",
                "region": "East",
                "province": "East - province 2",
                "city": "City 3",
                "district": "District 4",
                "some":"other"
            }
        ]
    },
    {
        "id": 4,
        "name": "Modern Trade",
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "Sales Channel",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "Disctrict 5",
        "children": [
            {
                "id": 249,
                "name": "MTL",
                "commercialNameLang1": "Makkah",
                "commercialNameLang2": "مكه",
                "dealerType": "mtl",
                "region": "North",
                "province": "North - province 1",
                "city": "City 5",
                "district": "District 6",
                "some":"other"
            },
            {
                "id": 252,
                "name": "MTL",
                "commercialNameLang1": "Madina",
                "commercialNameLang2": "المدينة المنورة",
                "dealerType": "mtl",
                "region": "North",
                "province": "North - province 1",
                "city": "City 5",
                "district": "District 6",
                "some":"other"
            },
            {
                "id": 285,
                "name": "Modern Trade Location",
                "commercialNameLang1": "Modern Trade Location name in englishh",
                "commercialNameLang2": "Modern Trade Location name in arabic",
                "dealerType": "MTL",
                "region": null,
                "province": null,
                "city": null,
                "district": null,
                "some":"other"
            },
            {
                "id": 294,
                "name": "Modern Trade name in english",
                "commercialNameLang1": "Modern Trade name in english",
                "commercialNameLang2": "Modern Trade name in arabic",
                "dealerType": "MTL",
                "region": null,
                "province": null,
                "city": null,
                "district": null,
                "some":"other"
            },
            {
                "id": 351,
                "name": "Modern Trade name in english",
                "commercialNameLang1": "Modern Trade name in english",
                "commercialNameLang2": "Modern Trade name in arabic",
                "dealerType": "MTL",
                "region": null,
                "province": null,
                "city": null,
                "district": null,
                "some":"other"
            }
        ]
    },
    {
        "id": 297,
        "name": null,
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "Distributor",
        "region": null,
        "province": null,
        "city": null,
        "district": null,
        "some":"other"
    },
    {
        "id": 300,
        "name": null,
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "distributor",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "District 4",
        "some":"other"
    },
    {
        "id": 303,
        "name": null,
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "distributor",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 306,
        "name": null,
        "commercialNameLang1": null,
        "commercialNameLang2": null,
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 2",
        "some":"other"
    },
    {
        "id": 309,
        "name": "some English",
        "commercialNameLang1": "some English",
        "commercialNameLang2": "some Arabic",
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 312,
        "name": "dealertype English",
        "commercialNameLang1": "dealertype English",
        "commercialNameLang2": "dealertype Arabic",
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 1",
        "city": "City 2",
        "district": "District 3",
        "some":"other"
    },
    {
        "id": 315,
        "name": "asdasdded",
        "commercialNameLang1": "asdasdded",
        "commercialNameLang2": "asdasdasdeded",
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 321,
        "name": "dealerType",
        "commercialNameLang1": "dealerType",
        "commercialNameLang2": "dealerType",
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 345,
        "name": "hamza",
        "commercialNameLang1": "hamza",
        "commercialNameLang2": "hamza",
        "dealerType": "MTL",
        "region": "East",
        "province": "East - province 2",
        "city": "City 3",
        "district": "District 4",
        "some":"other"
    },
    {
        "id": 357,
        "name": "aftab",
        "commercialNameLang1": "aftab",
        "commercialNameLang2": "aftab",
        "dealerType": "sub_distributor",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 360,
        "name": "aaa",
        "commercialNameLang1": "aaa",
        "commercialNameLang2": "aaaa",
        "dealerType": "sub_distributor",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 2",
        "some":"other"
    },
    {
        "id": 363,
        "name": "curat",
        "commercialNameLang1": "curat",
        "commercialNameLang2": "curat",
        "dealerType": "sub_distributor",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 366,
        "name": "aaaa",
        "commercialNameLang1": "aaaa",
        "commercialNameLang2": "aaaa",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 2",
        "district": "District 3",
        "some":"other"
    },
    {
        "id": 369,
        "name": "hasna",
        "commercialNameLang1": "hasna",
        "commercialNameLang2": "hasna",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 372,
        "name": "test pos shop",
        "commercialNameLang1": "test pos shop",
        "commercialNameLang2": "test pos shop arabic",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 375,
        "name": "kasldjf",
        "commercialNameLang1": "kasldjf",
        "commercialNameLang2": "asdasfas",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 378,
        "name": "testing pos shafiq english",
        "commercialNameLang1": "testing pos shafiq english",
        "commercialNameLang2": "testing pos shafiq arabic",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    },
    {
        "id": 381,
        "name": "ramzan pos english",
        "commercialNameLang1": "ramzan pos english",
        "commercialNameLang2": "ramzan pos arabic",
        "dealerType": "pos_shop",
        "region": "East",
        "province": "East - province 1",
        "city": "City 1",
        "district": "District 1",
        "some":"other"
    }
]
export default defaultArray;